have_fun: false
code_review:
  disable: false
  comment_severity_threshold: MEDIUM
  max_review_comments: 50
  pull_request_opened:
    help: false
    summary: true
    code_review: true
    include_drafts: false
ignore_patterns:
  - "docs/**"
  - "*.md"
  - "*.json"
  - "dist/**"
